### ISSUE TITLE
Remove most of examples and refactor the existing one

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/plate-tectonics#16]
Just leave a simulation example taking as params: 
* the seed, 
* width and height
* the output (b/w or colored)

**Comment by ftomassetti** [comment]
See http://upload.wikimedia.org/wikipedia/commons/1/1c/Earth_surface_NGDC_2000.jpg for the colored image to generate

**Comment by ftomassetti** [comment]
Done

**Comment by psi29a** [comment]
yay! :)

**Comment by ftomassetti** [comment]
Hopefully now plate-tectonics is more understandable and we can start improving it (would be nice to make it faster...)
