### ISSUE TITLE
Consider merging the python bindings in this project

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/plate-tectonics#20]
Basically pyplatec should be integrated in here.

The main challenge seems in CI integration (no support for multiple languages on Travis or AppVeyor).

**Comment by psi29a** [comment]
Is that the main challenge? We can run scripts, depending on OS, that will install the necessary development packages.

I know that OpenMW does additional building of gtest before getting to OpenMW itself, so this in theory shouldn't be too hard.

Is there something else that is the problem?

**Comment by ftomassetti** [comment]
Yes, this is what I am trying to do. With Travis is very easy to configure it to repeat the same task on 5 different machines each one with a different version of python OR to run the same task with 2 machines, one using clang the other one gcc. We can still have Travis handle one of this automatically and manually installing the packages for the other languages and this is what I am trying to do. It requires more work and the reporting is not that nice but it should work.

**Comment by psi29a** [comment]
I remember setting up tox to handle things for my python/twisted projects, maybe that would help?

**Comment by psi29a** [comment]
http://jsatt.com/blog/using-tox-with-travis-ci-to-test-django-apps/
^-- more info

My example project:
https://github.com/twisted/ldaptor

**Comment by ftomassetti** [comment]
I am taking a look to tox. We still have to install the interpreters/find
them on the CI machine.
My current problem is that tox runs the compilation from a temporary
directory it creates, and I need to convince it to copy also the parent
directory because the project looks like:
\ root
--> src (C++)
--> pybindings

tox.ini, setup.py and so on are under pybindings. Maybe I should move them
in the root.

Federico

On Thu, Apr 9, 2015 at 5:47 PM, Bret Curtis <notifications@github.com>
wrote:

> http://jsatt.com/blog/using-tox-with-travis-ci-to-test-django-apps/
> ^-- more info
>
> My example project:
> https://github.com/twisted/ldaptor
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mindwerks/plate-tectonics/issues/20#issuecomment-91288211>
> .
>



-- 
Website at http://tomassetti.me <http://www.federico-tomassetti.it>
GitHub https://github.com/ftomassetti

**Comment by ftomassetti** [comment]
Travis is almost ok (still problems with Python 2.6) but AppVeyor will take some time. We should becomes a super successful project and get donations to pay AppVeyor pro, because the free plan is way too slow

**Comment by ftomassetti** [comment]
We should be ready with #19

**Comment by ftomassetti** [comment]
It is now done.

**Comment by psi29a** [comment]
yay!
